# from django.db import models
import django.db.models


class Common(django.db.models.Model):
    """
    Abstract class for common attributes and behaviour
    """
    code = django.db.models.CharField(max_length=100, unique=False)
    # ...

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

    class Meta:
        abstract = True


class IndexCard(Common):
    """
    Represents Index Card Entry for a City to link index card with user
    """
    city = django.db.models.CharField(max_length=100, unique=True)
    username = django.db.models.CharField(max_length=100, unique=True)
    # name will be generated by code as concatenation of city and username


class Section(Common):
    """
    Represents a section (set of questions) in the index card
    """
    name = django.db.models.CharField(max_length=100, unique=False)
    index_card = django.db.models.ForeignKey(IndexCard)


class QuestionBase(Common):
    """
    Abstract class with basic elements of a question
    """
    statement = django.db.models.CharField(max_length=250, null=True, blank=True)
    answer = django.db.models.CharField(max_length=250, null=True, blank=True)
    section = django.db.models.ForeignKey(Section)

    class Meta:
        abstract = True


class QuestionShort(QuestionBase):
    """
    Represents a single question in a section with short answer
    """
    comments = django.db.models.CharField(max_length=250, null=True, blank=True)


class QuestionLong(QuestionBase):
    """
    Represents a single question in a section with long answer
    """
    comments = django.db.models.TextField(max_length=400, null=True, blank=True)


